-- Creamos la base de datos
CREATE DATABASE ESTADOS_64605;

-- Le indicamos a SQL MS que use la base de datos estados
USE ESTADOS_64605;

-- Creamos la tabla estados
CREATE TABLE ESTADOS (
ID_ESTADO INT NOT NULL PRIMARY KEY,
ESTADO VARCHAR(MAX)
);


-- Consulto la tabla estados
SELECT * FROM ESTADOS;


-- Creamos la tabla CIUDADES_USA
CREATE TABLE CIUDADES_USA (
ID_Ciudad INT NOT NULL PRIMARY KEY,
CIUDAD VARCHAR(MAX) NOT NULL,
VARIACION FLOAT,
ID_ESTADO INT NOT NULL,
AREA VARCHAR(255),
DENSIDAD_POBLACIONAL VARCHAR(255),
UBICACION VARCHAR(255)

CONSTRAINT FK_ESTADO FOREIGN KEY (ID_ESTADO)
REFERENCES ESTADOS(ID_ESTADO)
);

SELECT * FROM CIUDADES_USA;

CREATE TABLE DATOS_CENSO (
RANK INT NOT NULL PRIMARY KEY,
ID_Ciudad INT NOT NULL,
CENSO_2020 INT NOT NULL, --En SQL Server los nombres de columnas no puede empezar con número ni contener espacios. No puede ser 2020 Censo
CENSO_2010 INT NOT NULL

CONSTRAINT FK_CIUDADES FOREIGN KEY (ID_Ciudad)
REFERENCES CIUDADES_USA(ID_Ciudad)
);

SELECT * FROM DATOS_CENSO;

CREATE TABLE PAIS (
ID_PAIS INT NOT NULL PRIMARY KEY,
NOMBRE_PAIS VARCHAR(MAX) NOT NULL
);

SELECT * FROM PAIS;

INSERT INTO PAIS (ID_PAIS, NOMBRE_PAIS)
VALUES (1, 'Argentina'),
(2, 'Francia'),
(3, 'Inglaterra'),
(4, 'Londres'),
(5, 'Cardiff'),
(6, 'Reino Unido'),
(7, 'Estados Unidos'),
(8, 'Uruguay');


SELECT * FROM PAIS;

DROP TABLE PAIS;
DROP TABLE DATOS_CENSO;
DROP TABLE CIUDADES_USA;
DROP TABLE ESTADOS;

DROP DATABASE ESTADOS_64605;

SELECT * FROM ESTADOS;
SELECT * FROM CIUDADES_USA;
SELECT * FROM DATOS_CENSO;

ALTER TABLE CIUDADES_USA
ALTER COLUMN CIUDAD VARCHAR(MAX);

ALTER TABLE ESTADOS
ALTER COLUMN ESTADO VARCHAR(MAX);